# Generated by Django 4.0.5 on 2022-06-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplex', models.CharField(max_length=255)),
                ('movie_name', models.CharField(max_length=255)),
                ('cast', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('show_timing', models.DateTimeField()),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=255)),
                ('time_booked', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=255)),
                ('show_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.screens')),
            ],
        ),
    ]
